package com.analogics.paymentservicecore.model.emv

enum class DisplayMsgId {

    /* NFC Tip Messages */
    CARD_READ_OK,
    REMOVE_CARD,
    USE_CONTACT_IC_CARD,
    USE_MAG_STRIPE,
    INSERT_SWIPE_OR_TRY_ANOTHER_CARD,
    SEE_PHONE_AND_PRESENT_CARD_AGAIN,
    NEED_SIGNATURE,
    END_APPLICATION,
    DISPLAY_BALANCE,
    TAP_CARD_AGAIN,
    APP_BLOCKED,
    TERMINATED,

    /* Error Messages */
    ERR_CARD_READ,
    ERR_PROCESSING,
    ERR_LOAD_CALLBACK,
    ERR_ICS_PARAM_NOT_FOUND,
    ERR_KERNEL,
    ERR_PIN_LENGTH,
    ERR_MULTI_CARD,
    ERR_CHECK_CARD,
    ERR_AID_PARAM_NOT_FIND,
    ERR_CAPK_PARAM_NOT_FIND,
    ERR_GET_KERNEL_DATA_FAILED,
    ERR_QPBOC_APPLICATION,
    ERR_QPBOC_FDDA_FAILED,
    ERR_PURE_ELE_CASH_CARD_NOT_ALLOW_ONLINE_TRANS
}