package com.analogics.paymentservicecore.model.emv

enum class EmvTransResult {
    APPROVED_ONLINE,
    DECLINED_ONLINE,
    APPROVED_OFFLINE,
    DECLINED_OFFLINE,
    CANCELED,
    TIMEOUT,
    TERMINATED,
    CARD_BLOCKED,
    APP_BLOCKED,
    NO_EMV_APPS,
    APP_SELECTION_FAILED,
    TRY_ANOTHER_INTERFACE,
    INVALID_ICC_CARD,
    RETRY,
    CARD_REMOVED,
    ISSUER_SCRIPT_UPDATE_SUCCESSFUL,
    ISSUER_SCRIPT_UPDATE_FAILED
}