package com.eazypaytech.posafrica.core.navigation.utilities

enum class ScreensRouteTypes {
    SplashScreen,DashBoardScreen,OnBoardingScreen,LoginScreen,ForgetPasswordView,PleaseWaitScreen,AmountScreen,InvoiceView,ConfirmationScreen,TipScreen,ServiceChargeScreen,CardScreen,CardDetectScreen,PinScreen,ApprovedScreen,PasswordScreen,EmailScreen,RefundAmtScreen,SettingsScreen,LanguageScreen,ConfigurationScreen,ConfirmShiftScreen,TaxPercentageScreen,TipPercentageScreen,ServiceChargePercentageScreen,PreauthScreen,EnterEmailScreen,DeclineScreen,Drawer,TxnListScreen,InfoConfirmScreen,SucessScreen,ChangePasswordScreen,BarcodeScreen,TransactionDetailsScreen,ReceiptDetailsScreen,UserManagementScreen,BatchIdScreen,InactivityTimeoutScreen,SignatureScreen,EBTSelectionScreen,TxnSelectionScreen,KeyEntryScreen,VoucherCardScreen,AuthScreen
    ,AddClerkScreen,ActivationScreen,CashBackScreen,ManualCardScreen
}