package com.analogics.securityframework.database.entity

import androidx.room.ColumnInfo
import androidx.room.Entity
import androidx.room.PrimaryKey
import java.io.Serializable


@Entity(tableName = "TransactionReport")
data class TxnDtlsEntity(
    @PrimaryKey(autoGenerate = true) var id: Int? = null,
    @ColumnInfo(name = "POIId") var POIId: String? = null,
    @ColumnInfo(name = "MrchntId") var MrchntId: String? = null,
    @ColumnInfo(name = "CshrId") var CshrId: String? = null,
    @ColumnInfo(name = "InvcNb") var InvcNb: String? = null,
    @ColumnInfo(name = "PurchsOrdrNb") var PurchsOrdrNb: String? = null,
    @ColumnInfo(name = "SaleRefNb") var SaleRefNb: String? = null,
    @ColumnInfo(name = "SaleRefId") var SaleRefId: String? = null,
    @ColumnInfo(name = "ExchangeId") var ExchangeId: String? = null,
    @ColumnInfo(name = "PoiSerialNumber") var PoiSerialNumber: String? = null,
    @ColumnInfo(name = "PoiDeviceType") var PoiDeviceType: String? = null,
    @ColumnInfo(name = "TxnType") var TxnType: String? = null,
    @ColumnInfo(name = "TxRef") var TxRef: String? = null,
    @ColumnInfo(name = "TxDt") var TxDt: String? = null,
    @ColumnInfo(name = "TxTp") var TxTp: String? = null,
    @ColumnInfo(name = "AcctTp") var AcctTp: String? = null,
    @ColumnInfo(name = "TxnAmt") var TxnAmt: String? = null,
    @ColumnInfo(name = "TtlAmt") var TtlAmt: String? = null,
    @ColumnInfo(name = "Gratuity") var Gratuity: String? = "0.00",
    @ColumnInfo(name = "Cashback") var Cashback: String? = "0.00",
    @ColumnInfo(name = "Surcharge") var Surcharge: String? = "0.00",
    @ColumnInfo(name = "MskPan") var MskPan: String? = null,
    @ColumnInfo(name = "CardBrand") var CardBrand: String? = null,
    @ColumnInfo(name = "AppSpecificData") var AppSpecificData: String? = null,
    @ColumnInfo(name = "ICCRltdData") var ICCRltdData: String? = null,
    @ColumnInfo(name = "RcptICCRltdData") var RcptICCRltdData: String? = null,
    @ColumnInfo(name = "Signature") var Signature: String? = null,
    @ColumnInfo(name = "CardDataNtryMd") var CardDataNtryMd: String? = null,
    @ColumnInfo(name = "CardPres") var CardPres: String? = "0",
    @ColumnInfo(name = "CrdhldrPres") var CrdhldrPres: String? = "0",
    @ColumnInfo(name = "AuthntcnMtd") var AuthntcnMtd: String? = null,
    @ColumnInfo(name = "AuthntcnRslt") var AuthntcnRslt: String? = null,
    @ColumnInfo(name = "TmZone") var TmZone: String? = null,
    @ColumnInfo(name = "CardCtryCd") var CardCtryCd: String? = null,
    @ColumnInfo(name = "TxId") var TxId: String? = null,
    @ColumnInfo(name = "Rspn") var Rspn: String? = null,
    @ColumnInfo(name = "AuthstnCd") var AuthstnCd: String? = null,
    @ColumnInfo(name = "RcncltnId") var RcncltnId: String? = null,
    @ColumnInfo(name = "CardSchmeRslt") var CardSchmeRslt: String? = null,
    @ColumnInfo(name = "HostDecision") var HostDecision: String? = null,
    @ColumnInfo(name = "RespCode") var RespCode: String? = null,
    @ColumnInfo(name = "TxnStatus") var TxnStatus: String? = null,
    @ColumnInfo(name = "CardPdctPrfl") var CardPdctPrfl: String? = null,
    @ColumnInfo(name = "CcyCd") var CcyCd: String? = null,
    @ColumnInfo(typeAffinity = ColumnInfo.REAL,name = "CmltvTotAmt") var CmltvTotAmt: Double? = null,
    @ColumnInfo(name = "TtlNb") val TtlNb: Int? = 0,
    @ColumnInfo(name = "TypeTranTotals") var TypeTranTotals: String? = null,
    @ColumnInfo(name = "TicketNumber") var TicketNumber: String? = null,
    @ColumnInfo(name = "BalanceDue") var BalanceDue: String? = "0",
    @ColumnInfo(name = "OriginalAmt") var OriginalAmt: String? = "0",
    @ColumnInfo(name = "OriginalTxRef") var OriginalTxRef: String? = null,
    @ColumnInfo(name = "IsMoto") var IsMoto: Boolean? = false,
    @ColumnInfo(name = "LanguagePref") var LanguagePref: String? = null,
    @ColumnInfo(name = "SvcAttr") var SvcAttr: String? = null,
    @ColumnInfo(name = "IsFallback") var IsFallback: Boolean? = false,
    @ColumnInfo(name = "IsAuthCapture") var IsAuthCapture: Boolean? = false,
    @ColumnInfo(name = "IsVoided") var IsVoided: Boolean? = false,
    @ColumnInfo(name = "IsPrtlRefunded") var IsPrtlRefunded: Boolean? = false,
    @ColumnInfo(name = "IsRefunded") var IsRefunded: Boolean? = false,
    @ColumnInfo(name = "AuthResult") var AuthResult: String? = null,
    @ColumnInfo(name = "IsTipAdjust") var IsTipAdjust: Boolean? = false,

    ) : Serializable