package com.analogics.networkservicecore.di

import com.analogics.networkservicecore.tms.api.TmsApiService
import dagger.Module
import dagger.Provides
import dagger.hilt.InstallIn
import dagger.hilt.components.SingletonComponent
import okhttp3.OkHttpClient
import okhttp3.logging.HttpLoggingInterceptor
import retrofit2.Retrofit
import retrofit2.converter.gson.GsonConverterFactory
import java.util.concurrent.TimeUnit
import javax.inject.Singleton


/**
 * Hilt module responsible for providing TMS-specific network dependencies.
 *
 * This module is separated from general network module because:
 * - It uses a different base URL
 * - It may evolve independently (TMS APIs vs core APIs)
 */
@Module
@InstallIn(SingletonComponent::class)
object TmsNetworkModule {


    /**
     * Provides Retrofit instance specifically for TMS backend.
     *
     * Uses:
     * - Custom base URL
     * - OkHttp client with logging
     * - Gson converter for JSON parsing
     *
     * @TmsRetrofit qualifier ensures separation from other Retrofit instances
     */
    @Provides
    @Singleton
    @TmsRetrofit   // ✅ IMPORTANT
    fun provideTmsRetrofit(): Retrofit {

        val logging = HttpLoggingInterceptor().apply {
            level = HttpLoggingInterceptor.Level.BODY
        }

        val client = OkHttpClient.Builder()
            .connectTimeout(30, TimeUnit.SECONDS)
            .readTimeout(30, TimeUnit.SECONDS)
            .addInterceptor(logging)
            .build()

        return Retrofit.Builder()
            .baseUrl("https://unitms.morefun-et.com/") //
            .client(client)
            .addConverterFactory(GsonConverterFactory.create())
            .build()
    }

    /**
     * Provides TMS API service implementation generated by Retrofit.
     *
     * @param retrofit Injected TMS-specific Retrofit instance
     * @return TmsApiService implementation
     */
    @Provides
    @Singleton
    fun provideTmsApiService(
        @TmsRetrofit retrofit: Retrofit   // ✅ IMPORTANT
    ): TmsApiService {
        return retrofit.create(TmsApiService::class.java)
    }
}